Update pipImport.yml

diff --git a/.github/workflows/pipImport.yml b/.github/workflows/pipImport.yml
--- a/.github/workflows/pipImport.yml
+++ b/.github/workflows/pipImport.yml
@@ -28,21 +28,21 @@ jobs:
       - name: Check for new files in pipImport.py
         id: check_pip_files
         run: |
-          echo $(pwd)
-          if [[ ! -f "pipImport.py" ]]; then
-            echo "pipImport.py not found"
-            exit 1
-          fi
-          ls
-          echo "Searching for remote_repo in all files..."
-          grep -r "remote_repo" . | cat
-          pip_files=$(grep -oP ".remote_repo\(\['.*'\], '.*/$file'\)" -r . | grep '^src/' | grep -oP "(?<=from ).*(?= import)")
-          if [[ -z "$pip_files" ]]; then
-            echo "No files in pipImport.py"
-          else
-            echo "Files in pipImport.py:"
-            echo "$pip_files"
-          fi
+            echo $(pwd)
+            if [[ ! -f "pipImport.py" ]]; then
+              echo "pipImport.py not found"
+              exit 1
+            fi
+            ls
+            echo "Searching for remote_repo in all files..."
+            grep -r "remote_repo" . | cat
+            pip_files=$(grep -oP "(?<=remote_repo\(\[').*?(?='\],)" -r . | grep '^src/' | grep -oP "(?<=from ).*(?= import)")
+            if [[ -z "$pip_files" ]]; then
+              echo "No files in pipImport.py"
+            else
+              echo "Files in pipImport.py:"
+              echo "$pip_files"
+            fi
       - name: Add new file names to pipImport.py
         if: steps.check_files.outputs.files != ''
         run: |
